const wordList = [
  { word: "exact", phonetic: "/ɪɡˈzækt/", definition: "not approximated in any way; precise.", cn: "adj. 精确的" },
  { word: "burgeon", phonetic: "/ˈbɜːrdʒən/", definition: "begin to grow or increase rapidly; flourish.", cn: "v. 迅速成长" },
  { word: "hierarchy", phonetic: "/ˈhaɪərɑːrki/", definition: "a system in which members of an organization or society are ranked according to relative status or authority.", cn: "n. 层级" },
  { word: "chronic", phonetic: "/ˈkrɑːnɪk/", definition: "(of an illness) persisting for a long time or constantly recurring.", cn: "adj. 慢性的" },
  { word: "desirable", phonetic: "/dɪˈzaɪərəbl/", definition: "wished for as being an attractive, useful, or necessary course of action.", cn: "adj. 值得拥有的" },
  { word: "subliminal", phonetic: "/ˌsʌbˈlɪmɪnl/", definition: "(of a stimulus or mental process) below the threshold of sensation or consciousness; perceived by or affecting someone's mind without their being aware of it.", cn: "adj. 潜意识的" },
  { word: "frequent", phonetic: "/ˈfriːkwənt/", definition: "occurring or done on many occasions, in many cases, or in quick succession.", cn: "adj. 频繁的" },
  { word: "prosperous", phonetic: "/ˈprɑːspərəs/", definition: "successful in material terms; flourishing financially.", cn: "adj. 繁荣的" },
  { word: "resort", phonetic: "/rɪˈzɔːrt/", definition: "a place that is a popular destination for vacations or recreation, or which is frequented for a particular purpose.", cn: "n. 度假胜地" },
  { word: "equity", phonetic: "/ˈekwəti/", definition: "the quality of being fair and impartial.", cn: "n. 公平" },
  { word: "excavate", phonetic: "/ˈekskəveɪt/", definition: "make (a hole or channel) by digging.", cn: "v. 挖掘" },
  { word: "massive", phonetic: "/ˈmæsɪv/", definition: "large and heavy or solid.", cn: "adj. 巨大的" },
  { word: "companion", phonetic: "/kəmˈpænjən/", definition: "a person or animal with whom one spends a lot of time or with whom one travels.", cn: "n. 同伴" },
  { word: "rig", phonetic: "/rɪɡ/", definition: "make (a sailing ship or boat) ready for sailing by providing it with sails and rigging.", cn: "v. 操纵" },
  { word: "impart", phonetic: "/ɪmˈpɑːrt/", definition: "make (information) known; communicate.", cn: "v. 传授" },
  { word: "forfeit", phonetic: "/ˈfɔːrfɪt/", definition: "lose or be deprived of (property or a right or privilege) as a penalty for wrongdoing.", cn: "v. 丧失" },
  { word: "calorie", phonetic: "/ˈkæləri/", definition: "either of two units of heat energy.", cn: "n. 卡路里" },
  { word: "eternal", phonetic: "/ɪˈtɜːrnl/", definition: "lasting or existing forever; without end or beginning.", cn: "adj. 永恒的" },
  { word: "optional", phonetic: "/ˈɑːpʃənl/", definition: "available to be chosen but not obligatory.", cn: "adj. 可选的" },
  { word: "heal", phonetic: "/hiːl/", definition: "(of a wound or a person) become sound or healthy again.", cn: "v. 治愈" },
  { word: "dismantle", phonetic: "/dɪsˈmæntl/", definition: "take (a machine or structure) to pieces.", cn: "v. 拆除" },
  { word: "wage", phonetic: "/weɪdʒ/", definition: "a fixed regular payment, typically paid on a daily or weekly basis, made by an employer to an employee, especially to a manual or unskilled worker.", cn: "n. 工资" },
  { word: "commonwealth", phonetic: "/ˈkɑːmənwelθ/", definition: "an independent country or community, especially a democratic republic.", cn: "n. 联邦" },
  { word: "periodical", phonetic: "/ˌpɪriˈɑːdɪkl/", definition: "a magazine or newspaper published at regular intervals.", cn: "n. 期刊" },
  { word: "clip", phonetic: "/klɪp/", definition: "a device, typically of metal or plastic, for fixing items together or containing them.", cn: "n. 夹子" },
  { word: "secure", phonetic: "/sɪˈkjʊr/", definition: "fixed or fastened so as not to give way, become loose, or be lost.", cn: "adj. 安全的" },
  { word: "code", phonetic: "/koʊd/", definition: "a system of words, letters, figures, or other symbols substituted for other words, letters, etc., especially for the purposes of secrecy.", cn: "n. 代码" },
  { word: "crown", phonetic: "/kraʊn/", definition: "a circular ornamental headdress worn by monarchs as a symbol of authority, usually made of or decorated with precious metals and jewels.", cn: "n. 王冠" },
  { word: "margin", phonetic: "/ˈmɑːrdʒɪn/", definition: "the edge or border of something.", cn: "n. 边缘" },
  { word: "complicate", phonetic: "/ˈkɑːmplɪkeɪt/", definition: "make (something) more difficult or confusing by causing it to be more complex.", cn: "v. 使复杂" },
  { word: "maturity", phonetic: "/məˈtʃʊrəti/", definition: "the state, fact, or period of being mature.", cn: "n. 成熟" },
  { word: "evacuate", phonetic: "/ɪˈvækjueɪt/", definition: "remove (someone) from a place of danger to a safer place.", cn: "v. 疏散" },
  { word: "stint", phonetic: "/stɪnt/", definition: "a person's fixed or allotted period of work.", cn: "n. 定量" },
  { word: "squash", phonetic: "/skwɑːʃ/", definition: "crush or squeeze (something) with force so that it becomes flat, soft, or out of shape.", cn: "v. 压扁" },
  { word: "surge", phonetic: "/sɜːrdʒ/", definition: "a sudden powerful forward or upward movement, especially by a crowd or by a natural force such as the waves or tide.", cn: "n. 汹涌" },
  { word: "justify", phonetic: "/ˈdʒʌstɪfaɪ/", definition: "show or prove to be right or reasonable.", cn: "v. 证明...有理" },
  { word: "score", phonetic: "/skɔːr/", definition: "the number of points, goals, runs, etc., achieved in a game or by a team or an individual.", cn: "n. 得分" },
  { word: "stamp", phonetic: "/stæmp/", definition: "a small adhesive piece of paper stuck to something to show that an amount of money has been paid, in particular a postage stamp.", cn: "n. 邮票" },
  { word: "whistle", phonetic: "/ˈwɪsəl/", definition: "a clear, high-pitched sound made by forcing breath through a small hole between partly closed lips, or through a device such as a whistle.", cn: "n. 口哨" },
  { word: "ceremony", phonetic: "/ˈserəmoʊni/", definition: "a formal religious or public occasion, typically one celebrating a particular event or anniversary.", cn: "n. 典礼" },
  { word: "diagnose", phonetic: "/ˌdaɪəɡˈnoʊs/", definition: "identify the nature of (an illness or other problem) by examination of the symptoms.", cn: "v. 诊断" },
  { word: "denote", phonetic: "/dɪˈnoʊt/", definition: "be a sign of; indicate.", cn: "v. 表示" },
  { word: "ensure", phonetic: "/ɪnˈʃʊr/", definition: "make certain that (something) shall occur or be the case.", cn: "v. 确保" },
  { word: "accurate", phonetic: "/ˈækjərət/", definition: "(of information, measurements, statistics, etc.) correct in all details; exact.", cn: "adj. 准确的" },
  { word: "tender", phonetic: "/ˈtendər/", definition: "showing gentleness and concern or sympathy.", cn: "adj. 温柔的" },
  { word: "seep", phonetic: "/siːp/", definition: "(of a liquid) flow or leak slowly through porous material or small holes.", cn: "v. 渗透" },
  { word: "delinquency", phonetic: "/dɪˈlɪŋkwənsi/", definition: "minor crime, especially that committed by young people.", cn: "n. 失职" },
  { word: "deliberate", phonetic: "/dɪˈlɪbərət/", definition: "done consciously and intentionally.", cn: "adj. 故意的" },
  { word: "implication", phonetic: "/ˌɪmplɪˈkeɪʃn/", definition: "the conclusion that can be drawn from something, although it is not explicitly stated.", cn: "n. 含义" },
  { word: "opponent", phonetic: "/əˈpoʊnənt/", definition: "someone who competes against or fights another in a contest, game, or argument; a rival or adversary.", cn: "n. 对手" },
  { word: "substantial", phonetic: "/səbˈstænʃl/", definition: "of considerable importance, size, or worth.", cn: "adj. 大量的" },
  { word: "nurture", phonetic: "/ˈnɜːrtʃər/", definition: "care for and encourage the growth or development of.", cn: "v. 养育" },
  { word: "slight", phonetic: "/slaɪt/", definition: "small in degree; inconsiderable.", cn: "adj. 轻微的" },
  { word: "genetic", phonetic: "/dʒəˈnetɪk/", definition: "relating to genes or heredity.", cn: "adj. 遗传的" },
  { word: "leak", phonetic: "/liːk/", definition: "(of a container or covering) accidentally lose or admit contents, especially liquid or gas, through a hole or crack.", cn: "v. 泄漏" },
  { word: "impede", phonetic: "/ɪmˈpiːd/", definition: "delay or prevent (someone or something) by obstructing them; hinder.", cn: "v. 阻碍" },
  { word: "deduce", phonetic: "/dɪˈduːs/", definition: "arrive at (a fact or a conclusion) by reasoning; draw as a logical conclusion.", cn: "v. 推断" },
  { word: "absolute", phonetic: "/ˈæbsəluːt/", definition: "not qualified or diminished in any way; total.", cn: "adj. 绝对的" },
  { word: "theoretical", phonetic: "/ˌθiːəˈretɪkl/", definition: "concerned with or involving the theory of a subject or area of study rather than its practical application.", cn: "adj. 理论的" },
  { word: "respondent", phonetic: "/rɪˈspɑːndənt/", definition: "a defendant in a lawsuit, especially one in an appeals or divorce case.", cn: "n. 被告" }
];

export default wordList;