
const wordList = [
  { word: "exact", phonetic: "/ɪɡˈzækt/", definition: "not approximated in any way; precise.", cn: "adj. 精确的", example: "The exact time of the accident was 2:43 PM." },
  { word: "burgeon", phonetic: "/ˈbɜːrdʒən/", definition: "begin to grow or increase rapidly; flourish.", cn: "v. 迅速成长", example: "The town burgeoned into a city." },
  { word: "hierarchy", phonetic: "/ˈhaɪərɑːrki/", definition: "a system in which members of an organization or society are ranked according to relative status or authority.", cn: "n. 层级", example: "He was at the bottom of the corporate hierarchy." },
  { word: "chronic", phonetic: "/ˈkrɑːnɪk/", definition: "(of an illness) persisting for a long time or constantly recurring.", cn: "adj. 慢性的", example: "She suffers from chronic back pain." },
  { word: "desirable", phonetic: "/dɪˈzaɪərəbl/", definition: "wished for as being an attractive, useful, or necessary course of action.", cn: "adj. 值得拥有的", example: "The house has many desirable features." },
  { word: "subliminal", phonetic: "/ˌsʌbˈlɪmɪnl/", definition: "(of a stimulus or mental process) below the threshold of sensation or consciousness; perceived by or affecting someone's mind without their being aware of it.", cn: "adj. 潜意识的", example: "The advertisement used subliminal messages to sell its product." },
  { word: "frequent", phonetic: "/ˈfriːkwənt/", definition: "occurring or done on many occasions, in many cases, or in quick succession.", cn: "adj. 频繁的", example: "He is a frequent visitor to the museum." },
  { word: "prosperous", phonetic: "/ˈprɑːspərəs/", definition: "successful in material terms; flourishing financially.", cn: "adj. 繁荣的", example: "The company had a prosperous year." },
  { word: "resort", phonetic: "/rɪˈzɔːrt/", definition: "a place that is a popular destination for vacations or recreation, or which is frequented for a particular purpose.", cn: "n. 度假胜地", example: "We went to a ski resort for our vacation." },
  { word: "equity", phonetic: "/ˈekwəti/", definition: "the quality of being fair and impartial.", cn: "n. 公平", example: "The company is committed to equity in the workplace." },
  { word: "excavate", phonetic: "/ˈekskəveɪt/", definition: "make (a hole or channel) by digging.", cn: "v. 挖掘", example: "They excavated a trench to lay the new water pipe." },
  { word: "massive", phonetic: "/ˈmæsɪv/", definition: "large and heavy or solid.", cn: "adj. 巨大的", example: "The elephant is a massive animal." },
  { word: "companion", phonetic: "/kəmˈpænjən/", definition: "a person or animal with whom one spends a lot of time or with whom one travels.", cn: "n. 同伴", example: "His dog was his faithful companion." },
  { word: "rig", phonetic: "/rɪɡ/", definition: "make (a sailing ship or boat) ready for sailing by providing it with sails and rigging.", cn: "v. 操纵", example: "The sailors rigged the ship for the long voyage." },
  { word: "impart", phonetic: "/ɪmˈpɑːrt/", definition: "make (information) known; communicate.", cn: "v. 传授", example: "The teacher imparted her knowledge to the students." },
  { word: "forfeit", phonetic: "/ˈfɔːrfɪt/", definition: "lose or be deprived of (property or a right or privilege) as a penalty for wrongdoing.", cn: "v. 丧失", example: "He had to forfeit his driver's license for a year." },
  { word: "calorie", phonetic: "/ˈkæləri/", definition: "either of two units of heat energy.", cn: "n. 卡路里", example: "This meal is low in calories." },
  { word: "eternal", phonetic: "/ɪˈtɜːrnl/", definition: "lasting or existing forever; without end or beginning.", cn: "adj. 永恒的", example: "The couple exchanged vows of eternal love." },
  { word: "optional", phonetic: "/ˈɑːpʃənl/", definition: "available to be chosen but not obligatory.", cn: "adj. 可选的", example: "The final exam is optional." },
  { word: "heal", phonetic: "/hiːl/", definition: "(of a wound or a person) become sound or healthy again.", cn: "v. 治愈", example: "The wound healed quickly." },
  { word: "dismantle", phonetic: "/dɪsˈmæntl/", definition: "take (a machine or structure) to pieces.", cn: "v. 拆除", example: "They dismantled the old bridge." },
  { word: "wage", phonetic: "/weɪdʒ/", definition: "a fixed regular payment, typically paid on a daily or weekly basis, made by an employer to an employee, especially to a manual or unskilled worker.", cn: "n. 工资", example: "He earns a good wage." },
  { word: "commonwealth", phonetic: "/ˈkɑːmənwelθ/", definition: "an independent country or community, especially a democratic republic.", cn: "n. 联邦", example: "Australia is a member of the Commonwealth." },
  { word: "periodical", phonetic: "/ˌpɪriˈɑːdɪkl/", definition: "a magazine or newspaper published at regular intervals.", cn: "n. 期刊", example: "She subscribes to several periodicals." },
  { word: "clip", phonetic: "/klɪp/", definition: "a device, typically of metal or plastic, for fixing items together or containing them.", cn: "n. 夹子", example: "He used a clip to hold the papers together." },
  { word: "secure", phonetic: "/sɪˈkjʊr/", definition: "fixed or fastened so as not to give way, become loose, or be lost.", cn: "adj. 安全的", example: "The house is secure." },
  { word: "code", phonetic: "/koʊd/", definition: "a system of words, letters, figures, or other symbols substituted for other words, letters, etc., especially for the purposes of secrecy.", cn: "n. 代码", example: "The spy used a secret code." },
  { word: "crown", phonetic: "/kraʊn/", definition: "a circular ornamental headdress worn by monarchs as a symbol of authority, usually made of or decorated with precious metals and jewels.", cn: "n. 王冠", example: "The queen wore a beautiful crown." },
  { word: "margin", phonetic: "/ˈmɑːrdʒɪn/", definition: "the edge or border of something.", cn: "n. 边缘", example: "There is a wide margin on the left side of the page." },
  { word: "complicate", phonetic: "/ˈkɑːmplɪkeɪt/", definition: "make (something) more difficult or confusing by causing it to be more complex.", cn: "v. 使复杂", example: "Don't complicate the situation." },
  { word: "maturity", phonetic: "/məˈtʃʊrəti/", definition: "the state, fact, or period of being mature.", cn: "n. 成熟", example: "He has reached a level of emotional maturity." },
  { word: "evacuate", phonetic: "/ɪˈvækjueɪt/", definition: "remove (someone) from a place of danger to a safer place.", cn: "v. 疏散", example: "They evacuated the building during the fire." },
  { word: "stint", phonetic: "/stɪnt/", definition: "a person's fixed or allotted period of work.", cn: "n. 定量", example: "He did a two-year stint in the army." },
  { word: "squash", phonetic: "/skwɑːʃ/", definition: "crush or squeeze (something) with force so that it becomes flat, soft, or out of shape.", cn: "v. 压扁", example: "He squashed the spider with his shoe." },
  { word: "surge", phonetic: "/sɜːrdʒ/", definition: "a sudden powerful forward or upward movement, especially by a crowd or by a natural force such as the waves or tide.", cn: "n. 汹涌", example: "There was a surge of people towards the stage." },
  { word: "justify", phonetic: "/ˈdʒʌstɪfaɪ/", definition: "show or prove to be right or reasonable.", cn: "v. 证明...有理", example: "He tried to justify his actions." },
  { word: "score", phonetic: "/skɔːr/", definition: "the number of points, goals, runs, etc., achieved in a game or by a team or an individual.", cn: "n. 得分", example: "The final score was 3-0." },
  { word: "stamp", phonetic: "/stæmp/", definition: "a small adhesive piece of paper stuck to something to show that an amount of money has been paid, in particular a postage stamp.", cn: "n. 邮票", example: "He put a stamp on the envelope." },
  { word: "whistle", phonetic: "/ˈwɪsəl/", definition: "a clear, high-pitched sound made by forcing breath through a small hole between partly closed lips, or through a device such as a whistle.", cn: "n. 口哨", example: "The referee blew his whistle." },
  { word: "ceremony", phonetic: "/ˈserəmoʊni/", definition: "a formal religious or public occasion, typically one celebrating a particular event or anniversary.", cn: "n. 典礼", example: "The wedding ceremony was beautiful." },
  { word: "diagnose", phonetic: "/ˌdaɪəɡˈnoʊs/", definition: "identify the nature of (an illness or other problem) by examination of the symptoms.", cn: "v. 诊断", example: "The doctor diagnosed the illness as pneumonia." },
  { word: "denote", phonetic: "/dɪˈnoʊt/", definition: "be a sign of; indicate.", cn: "v. 表示", example: "A red cross denotes a hospital." },
  { word: "ensure", phonetic: "/ɪnˈʃʊr/", definition: "make certain that (something) shall occur or be the case.", cn: "v. 确保", example: "Please ensure that all the lights are turned off." },
  { word: "accurate", phonetic: "/ˈækjərət/", definition: "(of information, measurements, statistics, etc.) correct in all details; exact.", cn: "adj. 准确的", example: "The report is accurate." },
  { word: "tender", phonetic: "/ˈtendər/", definition: "showing gentleness and concern or sympathy.", cn: "adj. 温柔的", example: "She has a tender heart." },
  { word: "seep", phonetic: "/siːp/", definition: "(of a liquid) flow or leak slowly through porous material or small holes.", cn: "v. 渗透", example: "Water seeped through the cracks in the wall." },
  { word: "delinquency", phonetic: "/dɪˈlɪŋkwənsi/", definition: "minor crime, especially that committed by young people.", cn: "n. 失职", example: "Juvenile delinquency is a serious problem." },
  { word: "deliberate", phonetic: "/dɪˈlɪbərət/", definition: "done consciously and intentionally.", cn: "adj. 故意的", example: "It was a deliberate act of vandalism." },
  { word: "implication", phonetic: "/ˌɪmplɪˈkeɪʃn/", definition: "the conclusion that can be drawn from something, although it is not explicitly stated.", cn: "n. 含义", example: "The implication is that he is not to be trusted." },
  { word: "opponent", phonetic: "/əˈpoʊnənt/", definition: "someone who competes against or fights another in a contest, game, or argument; a rival or adversary.", cn: "n. 对手", example: "He beat his opponent in the final." },
  { word: "substantial", phonetic: "/səbˈstænʃl/", definition: "of considerable importance, size, or worth.", cn: "adj. 大量的", example: "He made a substantial donation to the charity." },
  { word: "nurture", phonetic: "/ˈnɜːrtʃər/", definition: "care for and encourage the growth or development of.", cn: "v. 养育", example: "She nurtured the young plants." },
  { word: "slight", phonetic: "/slaɪt/", definition: "small in degree; inconsiderable.", cn: "adj. 轻微的", example: "There is a slight chance of rain." },
  { word: "genetic", phonetic: "/dʒəˈnetɪk/", definition: "relating to genes or heredity.", cn: "adj. 遗传的", example: "The disease is genetic." },
  { word: "leak", phonetic: "/liːk/", definition: "(of a container or covering) accidentally lose or admit contents, especially liquid or gas, through a hole or crack.", cn: "v. 泄漏", example: "The roof is leaking." },
  { word: "impede", phonetic: "/ɪmˈpiːd/", definition: "delay or prevent (someone or something) by obstructing them; hinder.", cn: "v. 阻碍", example: "The bad weather impeded their progress." },
  { word: "deduce", phonetic: "/dɪˈduːs/", definition: "arrive at (a fact or a conclusion) by reasoning; draw as a logical conclusion.", cn: "v. 推断", example: "From the evidence, we can deduce that he is guilty." },
  { word: "absolute", phonetic: "/ˈæbsəluːt/", definition: "not qualified or diminished in any way; total.", cn: "adj. 绝对的", example: "I have absolute confidence in her." },
  { word: "theoretical", phonetic: "/ˌθiːəˈretɪkl/", definition: "concerned with or involving the theory of a subject or area of study rather than its practical application.", cn: "adj. 理论的", example: "The book is too theoretical." },
  { word: "respondent", phonetic: "/rɪˈspɑːndənt/", definition: "a defendant in a lawsuit, especially one in an appeals or divorce case.", cn: "n. 被告", example: "The respondent was ordered to pay damages." }
];

export default wordList;
